# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent_manager.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'agent_manager.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61gent_manager.proto\x12\rgenai.manager\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0c\x63ommon.proto\"D\n\x10RegisterResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x13\n\x0b\x61ssigned_id\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\":\n\x10HeartbeatRequest\x12&\n\x05\x61gent\x18\x01 \x01(\x0b\x32\x17.genai.common.AgentInfo\"%\n\x11HeartbeatResponse\x12\x10\n\x08\x63ommands\x18\x01 \x03(\t\"N\n\x0e\x41ssignResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x19\n\x11\x61ssigned_agent_id\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"4\n\tAgentList\x12\'\n\x06\x61gents\x18\x01 \x03(\x0b\x32\x17.genai.common.AgentInfo\"8\n\x13TaskProgressRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x10\n\x08\x61gent_id\x18\x02 \x01(\t2\x8b\x03\n\x0c\x41gentManager\x12I\n\rRegisterAgent\x12\x17.genai.common.AgentInfo\x1a\x1f.genai.manager.RegisterResponse\x12R\n\tHeartbeat\x12\x1f.genai.manager.HeartbeatRequest\x1a .genai.manager.HeartbeatResponse(\x01\x30\x01\x12\x46\n\nAssignTask\x12\x19.genai.common.TaskRequest\x1a\x1d.genai.manager.AssignResponse\x12>\n\nListAgents\x12\x16.google.protobuf.Empty\x1a\x18.genai.manager.AgentList\x12T\n\x0eStreamProgress\x12\".genai.manager.TaskProgressRequest\x1a\x1c.genai.common.ProgressUpdate0\x01\x42&\n\rgenai.managerZ\x15genai/manager;managerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_manager_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\rgenai.managerZ\025genai/manager;manager'
  _globals['_REGISTERRESPONSE']._serialized_start=81
  _globals['_REGISTERRESPONSE']._serialized_end=149
  _globals['_HEARTBEATREQUEST']._serialized_start=151
  _globals['_HEARTBEATREQUEST']._serialized_end=209
  _globals['_HEARTBEATRESPONSE']._serialized_start=211
  _globals['_HEARTBEATRESPONSE']._serialized_end=248
  _globals['_ASSIGNRESPONSE']._serialized_start=250
  _globals['_ASSIGNRESPONSE']._serialized_end=328
  _globals['_AGENTLIST']._serialized_start=330
  _globals['_AGENTLIST']._serialized_end=382
  _globals['_TASKPROGRESSREQUEST']._serialized_start=384
  _globals['_TASKPROGRESSREQUEST']._serialized_end=440
  _globals['_AGENTMANAGER']._serialized_start=443
  _globals['_AGENTMANAGER']._serialized_end=838
# @@protoc_insertion_point(module_scope)
