# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x0cgenai.common\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa2\x01\n\tAgentInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12%\n\x04type\x18\x03 \x01(\x0e\x32\x17.genai.common.AgentType\x12\x0f\n\x07version\x18\x04 \x01(\t\x12\x14\n\x0c\x63\x61pabilities\x18\x05 \x01(\t\x12-\n\tlast_seen\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"8\n\x07\x46ileRef\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12\x0c\n\x04mime\x18\x02 \x01(\t\x12\x12\n\nsize_bytes\x18\x03 \x01(\x03\"\xa6\x01\n\x0bTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x17\n\x0f\x61gent_type_hint\x18\x02 \x01(\t\x12$\n\x05input\x18\x03 \x01(\x0b\x32\x15.genai.common.FileRef\x12\x17\n\x0fparameters_json\x18\x04 \x01(\t\x12.\n\ncreated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x9d\x01\n\x0eProgressUpdate\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12(\n\x06status\x18\x02 \x01(\x0e\x32\x18.genai.common.TaskStatus\x12\x0f\n\x07percent\x18\x03 \x01(\x05\x12\x0f\n\x07message\x18\x04 \x01(\t\x12.\n\nupdated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xa0\x01\n\nTaskResult\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x12\n\noutput_uri\x18\x03 \x01(\t\x12\x13\n\x0bresult_json\x18\x04 \x01(\t\x12\x15\n\rerror_message\x18\x05 \x01(\t\x12\x30\n\x0c\x63ompleted_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x07\n\x05\x45mpty*u\n\tAgentType\x12\x15\n\x11\x41GENT_UNSPECIFIED\x10\x00\x12\x17\n\x13\x41GENT_TRANSCRIPTION\x10\x01\x12\x10\n\x0c\x41GENT_VISION\x10\x02\x12\x14\n\x10\x41GENT_GENERATION\x10\x03\x12\x10\n\x0c\x41GENT_CUSTOM\x10\x64*z\n\nTaskStatus\x12\x10\n\x0cTASK_UNKNOWN\x10\x00\x12\x0f\n\x0bTASK_QUEUED\x10\x01\x12\x10\n\x0cTASK_RUNNING\x10\x02\x12\x12\n\x0eTASK_SUCCEEDED\x10\x03\x12\x0f\n\x0bTASK_FAILED\x10\x04\x12\x12\n\x0eTASK_CANCELLED\x10\x05\x42#\n\x0cgenai.commonZ\x13genai/common;commonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\014genai.commonZ\023genai/common;common'
  _globals['_AGENTTYPE']._serialized_start=787
  _globals['_AGENTTYPE']._serialized_end=904
  _globals['_TASKSTATUS']._serialized_start=906
  _globals['_TASKSTATUS']._serialized_end=1028
  _globals['_AGENTINFO']._serialized_start=64
  _globals['_AGENTINFO']._serialized_end=226
  _globals['_FILEREF']._serialized_start=228
  _globals['_FILEREF']._serialized_end=284
  _globals['_TASKREQUEST']._serialized_start=287
  _globals['_TASKREQUEST']._serialized_end=453
  _globals['_PROGRESSUPDATE']._serialized_start=456
  _globals['_PROGRESSUPDATE']._serialized_end=613
  _globals['_TASKRESULT']._serialized_start=616
  _globals['_TASKRESULT']._serialized_end=776
  _globals['_EMPTY']._serialized_start=778
  _globals['_EMPTY']._serialized_end=785
# @@protoc_insertion_point(module_scope)
