# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: generation.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'generation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10generation.proto\x12\x10genai.generation\x1a\x0c\x63ommon.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"G\n\nPDFRequest\x12\'\n\x04task\x18\x01 \x01(\x0b\x32\x19.genai.common.TaskRequest\x12\x10\n\x08template\x18\x02 \x01(\t\"\\\n\x0bPPTXRequest\x12\'\n\x04task\x18\x01 \x01(\x0b\x32\x19.genai.common.TaskRequest\x12\x12\n\nmax_slides\x18\x02 \x01(\x05\x12\x10\n\x08template\x18\x03 \x01(\t\"\x81\x01\n\x10GenerationResult\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12%\n\x06output\x18\x03 \x01(\x0b\x32\x15.genai.common.FileRef\x12\x15\n\rmetadata_json\x18\x04 \x01(\t\x12\r\n\x05\x65rror\x18\x05 \x01(\t\"]\n\x0eSummaryRequest\x12\'\n\x04task\x18\x01 \x01(\x0b\x32\x19.genai.common.TaskRequest\x12\x0e\n\x06prompt\x18\x02 \x01(\t\x12\x12\n\nmax_tokens\x18\x03 \x01(\x05\"M\n\x0fSummaryResponse\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x14\n\x0csummary_text\x18\x02 \x01(\t\x12\x13\n\x0bresult_json\x18\x03 \x01(\t2\x8d\x02\n\x0fGenerationAgent\x12O\n\x0bGeneratePDF\x12\x1c.genai.generation.PDFRequest\x1a\".genai.generation.GenerationResult\x12Q\n\x0cGeneratePPTX\x12\x1d.genai.generation.PPTXRequest\x1a\".genai.generation.GenerationResult\x12V\n\x0fGenerateSummary\x12 .genai.generation.SummaryRequest\x1a!.genai.generation.SummaryResponseB/\n\x10genai.generationZ\x1bgenai/generation;generationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'generation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020genai.generationZ\033genai/generation;generation'
  _globals['_PDFREQUEST']._serialized_start=85
  _globals['_PDFREQUEST']._serialized_end=156
  _globals['_PPTXREQUEST']._serialized_start=158
  _globals['_PPTXREQUEST']._serialized_end=250
  _globals['_GENERATIONRESULT']._serialized_start=253
  _globals['_GENERATIONRESULT']._serialized_end=382
  _globals['_SUMMARYREQUEST']._serialized_start=384
  _globals['_SUMMARYREQUEST']._serialized_end=477
  _globals['_SUMMARYRESPONSE']._serialized_start=479
  _globals['_SUMMARYRESPONSE']._serialized_end=556
  _globals['_GENERATIONAGENT']._serialized_start=559
  _globals['_GENERATIONAGENT']._serialized_end=828
# @@protoc_insertion_point(module_scope)
