# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import generation_pb2 as generation__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in generation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GenerationAgentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GeneratePDF = channel.unary_unary(
                '/genai.generation.GenerationAgent/GeneratePDF',
                request_serializer=generation__pb2.PDFRequest.SerializeToString,
                response_deserializer=generation__pb2.GenerationResult.FromString,
                _registered_method=True)
        self.GeneratePPTX = channel.unary_unary(
                '/genai.generation.GenerationAgent/GeneratePPTX',
                request_serializer=generation__pb2.PPTXRequest.SerializeToString,
                response_deserializer=generation__pb2.GenerationResult.FromString,
                _registered_method=True)
        self.GenerateSummary = channel.unary_unary(
                '/genai.generation.GenerationAgent/GenerateSummary',
                request_serializer=generation__pb2.SummaryRequest.SerializeToString,
                response_deserializer=generation__pb2.SummaryResponse.FromString,
                _registered_method=True)


class GenerationAgentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GeneratePDF(self, request, context):
        """Generate a PDF summary
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GeneratePPTX(self, request, context):
        """Generate PowerPoint
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateSummary(self, request, context):
        """Generate short textual summary or answer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GenerationAgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GeneratePDF': grpc.unary_unary_rpc_method_handler(
                    servicer.GeneratePDF,
                    request_deserializer=generation__pb2.PDFRequest.FromString,
                    response_serializer=generation__pb2.GenerationResult.SerializeToString,
            ),
            'GeneratePPTX': grpc.unary_unary_rpc_method_handler(
                    servicer.GeneratePPTX,
                    request_deserializer=generation__pb2.PPTXRequest.FromString,
                    response_serializer=generation__pb2.GenerationResult.SerializeToString,
            ),
            'GenerateSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateSummary,
                    request_deserializer=generation__pb2.SummaryRequest.FromString,
                    response_serializer=generation__pb2.SummaryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'genai.generation.GenerationAgent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('genai.generation.GenerationAgent', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GenerationAgent(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GeneratePDF(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/genai.generation.GenerationAgent/GeneratePDF',
            generation__pb2.PDFRequest.SerializeToString,
            generation__pb2.GenerationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GeneratePPTX(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/genai.generation.GenerationAgent/GeneratePPTX',
            generation__pb2.PPTXRequest.SerializeToString,
            generation__pb2.GenerationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/genai.generation.GenerationAgent/GenerateSummary',
            generation__pb2.SummaryRequest.SerializeToString,
            generation__pb2.SummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
