# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transcription.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'transcription.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13transcription.proto\x12\x13genai.transcription\x1a\x0c\x63ommon.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"@\n\x15TaskTranscribeRequest\x12\'\n\x04task\x18\x01 \x01(\x0b\x32\x19.genai.common.TaskRequest\"\x86\x01\n\x17StreamTranscribeRequest\x12\'\n\x04task\x18\x01 \x01(\x0b\x32\x19.genai.common.TaskRequest\x12\x13\n\x0b\x61udio_chunk\x18\x02 \x01(\x0c\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xb7\x01\n\x12TranscriptionChunk\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x01\x12\x10\n\x08is_final\x18\x04 \x01(\x08\x12.\n\nstart_time\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x65nd_time\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xb8\x01\n\x13TranscriptionResult\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x39\n\x08segments\x18\x02 \x03(\x0b\x32\'.genai.transcription.TranscriptionChunk\x12\x1c\n\x14transcript_json_path\x18\x03 \x01(\t\x12(\n\x06status\x18\x04 \x01(\x0e\x32\x18.genai.common.TaskStatus\x12\r\n\x05\x65rror\x18\x05 \x01(\t2\xe5\x01\n\x12TranscriptionAgent\x12\x62\n\nTranscribe\x12*.genai.transcription.TaskTranscribeRequest\x1a(.genai.transcription.TranscriptionResult\x12k\n\x10StreamTranscribe\x12,.genai.transcription.StreamTranscribeRequest\x1a\'.genai.transcription.TranscriptionChunk0\x01\x42\x38\n\x13genai.transcriptionZ!genai/transcription;transcriptionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transcription_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023genai.transcriptionZ!genai/transcription;transcription'
  _globals['_TASKTRANSCRIBEREQUEST']._serialized_start=91
  _globals['_TASKTRANSCRIBEREQUEST']._serialized_end=155
  _globals['_STREAMTRANSCRIBEREQUEST']._serialized_start=158
  _globals['_STREAMTRANSCRIBEREQUEST']._serialized_end=292
  _globals['_TRANSCRIPTIONCHUNK']._serialized_start=295
  _globals['_TRANSCRIPTIONCHUNK']._serialized_end=478
  _globals['_TRANSCRIPTIONRESULT']._serialized_start=481
  _globals['_TRANSCRIPTIONRESULT']._serialized_end=665
  _globals['_TRANSCRIPTIONAGENT']._serialized_start=668
  _globals['_TRANSCRIPTIONAGENT']._serialized_end=897
# @@protoc_insertion_point(module_scope)
