# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import transcription_pb2 as transcription__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in transcription_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TranscriptionAgentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Transcribe = channel.unary_unary(
                '/genai.transcription.TranscriptionAgent/Transcribe',
                request_serializer=transcription__pb2.TaskTranscribeRequest.SerializeToString,
                response_deserializer=transcription__pb2.TranscriptionResult.FromString,
                _registered_method=True)
        self.StreamTranscribe = channel.unary_stream(
                '/genai.transcription.TranscriptionAgent/StreamTranscribe',
                request_serializer=transcription__pb2.StreamTranscribeRequest.SerializeToString,
                response_deserializer=transcription__pb2.TranscriptionChunk.FromString,
                _registered_method=True)


class TranscriptionAgentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Transcribe(self, request, context):
        """One-shot transcription (blocking until done)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTranscribe(self, request, context):
        """Streaming transcription: client sends audio frames or a single TaskRequest and receives a stream of partial results
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TranscriptionAgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Transcribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Transcribe,
                    request_deserializer=transcription__pb2.TaskTranscribeRequest.FromString,
                    response_serializer=transcription__pb2.TranscriptionResult.SerializeToString,
            ),
            'StreamTranscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTranscribe,
                    request_deserializer=transcription__pb2.StreamTranscribeRequest.FromString,
                    response_serializer=transcription__pb2.TranscriptionChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'genai.transcription.TranscriptionAgent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('genai.transcription.TranscriptionAgent', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TranscriptionAgent(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Transcribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/genai.transcription.TranscriptionAgent/Transcribe',
            transcription__pb2.TaskTranscribeRequest.SerializeToString,
            transcription__pb2.TranscriptionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTranscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/genai.transcription.TranscriptionAgent/StreamTranscribe',
            transcription__pb2.StreamTranscribeRequest.SerializeToString,
            transcription__pb2.TranscriptionChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
