# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import vision_pb2 as vision__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vision_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VisionAgentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeVideo = channel.unary_unary(
                '/genai.vision.VisionAgent/AnalyzeVideo',
                request_serializer=vision__pb2.VideoAnalysisRequest.SerializeToString,
                response_deserializer=vision__pb2.VisionResult.FromString,
                _registered_method=True)
        self.DetectGraphs = channel.unary_unary(
                '/genai.vision.VisionAgent/DetectGraphs',
                request_serializer=vision__pb2.VideoAnalysisRequest.SerializeToString,
                response_deserializer=vision__pb2.GraphDetectionResult.FromString,
                _registered_method=True)
        self.StreamAnalyze = channel.unary_stream(
                '/genai.vision.VisionAgent/StreamAnalyze',
                request_serializer=vision__pb2.VideoAnalysisRequest.SerializeToString,
                response_deserializer=vision__pb2.VisionChunk.FromString,
                _registered_method=True)


class VisionAgentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AnalyzeVideo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectGraphs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAnalyze(self, request, context):
        """Optionally stream incremental frame analysis
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VisionAgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeVideo': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeVideo,
                    request_deserializer=vision__pb2.VideoAnalysisRequest.FromString,
                    response_serializer=vision__pb2.VisionResult.SerializeToString,
            ),
            'DetectGraphs': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectGraphs,
                    request_deserializer=vision__pb2.VideoAnalysisRequest.FromString,
                    response_serializer=vision__pb2.GraphDetectionResult.SerializeToString,
            ),
            'StreamAnalyze': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamAnalyze,
                    request_deserializer=vision__pb2.VideoAnalysisRequest.FromString,
                    response_serializer=vision__pb2.VisionChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'genai.vision.VisionAgent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('genai.vision.VisionAgent', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VisionAgent(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzeVideo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/genai.vision.VisionAgent/AnalyzeVideo',
            vision__pb2.VideoAnalysisRequest.SerializeToString,
            vision__pb2.VisionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectGraphs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/genai.vision.VisionAgent/DetectGraphs',
            vision__pb2.VideoAnalysisRequest.SerializeToString,
            vision__pb2.GraphDetectionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamAnalyze(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/genai.vision.VisionAgent/StreamAnalyze',
            vision__pb2.VideoAnalysisRequest.SerializeToString,
            vision__pb2.VisionChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
